/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ClawdianPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/components/PairingModal.ts
var import_obsidian = require("obsidian");
var PairingModal = class extends import_obsidian.Modal {
  constructor(app, deviceId, onComplete) {
    super(app);
    this.checkInterval = null;
    this.deviceId = deviceId;
    this.onComplete = onComplete;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Connect to OpenClaw" });
    contentEl.createEl("p", {
      text: "Your device needs to be paired with the Gateway. Run this command in your terminal:"
    });
    const cmdEl = contentEl.createEl("div", { cls: "clawdian-terminal-command" });
    cmdEl.createEl("code", { text: `openclaw pairing approve ${this.deviceId}` });
    contentEl.createEl("div", {
      cls: "clawdian-pairing-code-label",
      text: `Device ID: ${this.deviceId}`
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Copy Command").setCta().onClick(() => {
        navigator.clipboard.writeText(`openclaw pairing approve ${this.deviceId}`);
        new import_obsidian.Notice("Command copied!");
      });
    });
    const statusEl = contentEl.createEl("div", {
      cls: "clawdian-pairing-status",
      text: "Waiting for approval..."
    });
    contentEl.createEl("h3", { text: "Or enter token manually:" });
    let tokenInput;
    new import_obsidian.Setting(contentEl).addText((text) => {
      tokenInput = text.inputEl;
      text.setPlaceholder("device-token-here");
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Use Token").onClick(() => {
        const token = tokenInput.value.trim();
        if (token) {
          this.onComplete();
          this.close();
        }
      });
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Cancel").onClick(() => this.close());
    });
    this.checkInterval = window.setInterval(() => {
    }, 2e3);
  }
  onClose() {
    if (this.checkInterval) {
      window.clearInterval(this.checkInterval);
    }
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  gatewayUrl: "ws://127.0.0.1:18789",
  gatewayToken: "",
  defaultAgent: "",
  includeVaultContext: true,
  autoConnect: false
};
var ClawdianSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Clawdian Settings" });
    const statusSection = containerEl.createEl("div", { cls: "clawdian-settings-section" });
    statusSection.createEl("h3", { text: "Connection Status" });
    const deviceId = this.plugin.client.getDeviceId();
    const isConnected = this.plugin.client.isConnected();
    new import_obsidian2.Setting(statusSection).setName("Status").setDesc(isConnected ? "\u2705 Connected" : "\u274C Disconnected");
    new import_obsidian2.Setting(statusSection).addButton((btn) => {
      if (isConnected) {
        btn.setButtonText("Disconnect").onClick(() => {
          this.plugin.client.disconnect();
          new import_obsidian2.Notice("Disconnected");
          this.display();
        });
      } else {
        btn.setButtonText("Connect").setCta().onClick(() => {
          this.plugin.tryConnect().then(() => {
            this.display();
          });
        });
      }
    });
    if (deviceId) {
      new import_obsidian2.Setting(statusSection).setName("Device ID").setDesc(deviceId).addButton((btn) => {
        btn.setButtonText("Copy").onClick(() => {
          navigator.clipboard.writeText(deviceId);
          new import_obsidian2.Notice("Device ID copied!");
        });
      });
    }
    containerEl.createEl("h3", { text: "Gateway Configuration" });
    new import_obsidian2.Setting(containerEl).setName("Gateway URL").setDesc("OpenClaw Gateway WebSocket URL").addText((text) => text.setPlaceholder("ws://127.0.0.1:18789").setValue(this.plugin.settings.gatewayUrl).onChange(async (value) => {
      this.plugin.settings.gatewayUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Gateway Token (optional)").setDesc("Only needed if auto-pairing fails").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("device-token").setValue(this.plugin.settings.gatewayToken).onChange(async (value) => {
        this.plugin.settings.gatewayToken = value;
        await this.plugin.saveSettings();
      });
    }).addButton((btn) => {
      btn.setButtonText("Test Connection").onClick(() => {
        this.plugin.client.updateConfig(
          this.plugin.settings.gatewayUrl,
          this.plugin.settings.gatewayToken
        );
        this.plugin.client.connect().then(() => {
          new import_obsidian2.Notice("\u2705 Connected successfully!");
          this.display();
        }).catch((err) => {
          new import_obsidian2.Notice("\u274C Connection failed: " + err.message);
          if (deviceId) {
            new PairingModal(this.app, deviceId, () => {
              this.plugin.client.clearDeviceToken();
              this.plugin.client.connect();
            }).open();
          }
        });
      });
    });
    containerEl.createEl("h3", { text: "Preferences" });
    const agentSetting = new import_obsidian2.Setting(containerEl).setName("Default Agent").setDesc("Which agent to chat with by default");
    const agents = this.plugin.client.getAgents();
    const dropdown = agentSetting.addDropdown((dropdown2) => {
      if (agents.length > 0) {
        agents.forEach((agent) => {
          dropdown2.addOption(agent.id, agent.name || agent.id);
        });
      } else {
        dropdown2.addOption("", "No agents available");
      }
      dropdown2.setValue(this.plugin.settings.defaultAgent);
      dropdown2.onChange(async (value) => {
        this.plugin.settings.defaultAgent = value;
        await this.plugin.saveSettings();
      });
      return dropdown2;
    });
    new import_obsidian2.Setting(containerEl).setName("Include vault context").setDesc("Send current file and vault info with messages").addToggle((toggle) => toggle.setValue(this.plugin.settings.includeVaultContext).onChange(async (value) => {
      this.plugin.settings.includeVaultContext = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Auto-connect on startup").setDesc("Automatically connect to Gateway when Obsidian starts").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoConnect).onChange(async (value) => {
      this.plugin.settings.autoConnect = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Advanced" });
    new import_obsidian2.Setting(containerEl).setName("Reset Device Identity").setDesc("Clear stored device identity and token").addButton((btn) => {
      btn.setButtonText("Reset").setWarning().onClick(() => {
        this.plugin.client["deviceManager"].clearIdentity();
        new import_obsidian2.Notice("Device identity cleared. Restart plugin to re-pair.");
        this.display();
      });
    });
  }
};

// src/components/ChatView.ts
var import_obsidian4 = require("obsidian");

// src/components/SetupCodeModal.ts
var import_obsidian3 = require("obsidian");
var SetupCodeModal = class extends import_obsidian3.Modal {
  constructor(app, onSetupComplete) {
    super(app);
    this.onSetupComplete = onSetupComplete;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Connect with Setup Code" });
    contentEl.createEl("p", {
      text: "To connect to your OpenClaw Gateway, run /pair in your OpenClaw chat (Discord, Signal, etc.) and paste the setup code below."
    });
    let codeInput;
    new import_obsidian3.Setting(contentEl).setName("Setup Code").setDesc("Paste the code from /pair command").addTextArea((text) => {
      codeInput = text.inputEl;
      text.setPlaceholder("eyJ1cmwiOiJ3c3M6Ly8...");
      codeInput.rows = 4;
      codeInput.style.fontFamily = "var(--font-monospace)";
    });
    new import_obsidian3.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Connect").setCta().onClick(() => {
        const code = codeInput.value.trim();
        if (!code) {
          new import_obsidian3.Notice("Please enter a setup code");
          return;
        }
        try {
          const data = this.decodeSetupCode(code);
          if (!data.url || !data.token) {
            new import_obsidian3.Notice("Invalid setup code: missing URL or token");
            return;
          }
          this.onSetupComplete(data.url, data.token);
          new import_obsidian3.Notice("\u2705 Connected!");
          this.close();
        } catch (err) {
          new import_obsidian3.Notice("Invalid setup code: " + err.message);
        }
      });
    }).addButton((btn) => {
      btn.setButtonText("Cancel").onClick(() => this.close());
    });
    contentEl.createEl("h3", { text: "How to get a setup code:" });
    const ol = contentEl.createEl("ol");
    ol.createEl("li", { text: "Open your OpenClaw chat (Discord, Signal, etc.)" });
    ol.createEl("li", { text: "Type: /pair" });
    ol.createEl("li", { text: "Copy the setup code that appears" });
    ol.createEl("li", { text: "Paste it here and click Connect" });
  }
  /**
   * Decode base64 setup code
   */
  decodeSetupCode(code) {
    try {
      const padding = 4 - code.length % 4;
      if (padding !== 4) {
        code += "=".repeat(padding);
      }
      const json = atob(code);
      return JSON.parse(json);
    } catch (err) {
      throw new Error("Failed to decode setup code");
    }
  }
};

// src/components/ChatView.ts
var VIEW_TYPE_CHAT = "clawdian-chat-view";
var ChatView = class extends import_obsidian4.ItemView {
  constructor(leaf, client, plugin) {
    super(leaf);
    this.connectPromptEl = null;
    this.inputContainerEl = null;
    this.deviceIdDisplayEl = null;
    this.agentSelectEl = null;
    this.loadingEl = null;
    this.isLoading = false;
    this.lastProcessedRunId = null;
    this.client = client;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "Clawdian Chat";
  }
  getIcon() {
    return "message-square";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("clawdian-chat-container");
    const header = container.createEl("div", { cls: "clawdian-header" });
    header.createEl("span", { text: "\u{1F99E} Clawdian", cls: "clawdian-title" });
    this.agentSelectEl = header.createEl("select", { cls: "clawdian-agent-select" });
    this.populateAgentDropdown();
    this.agentSelectEl.addEventListener("change", (e) => {
      this.plugin.settings.defaultAgent = e.target.value;
      this.plugin.saveSettings();
    });
    this.messagesEl = container.createEl("div", { cls: "clawdian-messages" });
    this.connectPromptEl = this.messagesEl.createEl("div", {
      cls: "clawdian-connect-prompt"
    });
    const statusIcon = this.connectPromptEl.createEl("div", { cls: "clawdian-status-icon" });
    (0, import_obsidian4.setIcon)(statusIcon, "plug");
    this.connectPromptEl.createEl("h3", { text: "Not Connected", cls: "clawdian-connect-title" });
    this.connectPromptEl.createEl("p", {
      text: "Click Connect to start chatting with your OpenClaw agents.",
      cls: "clawdian-connect-desc"
    });
    this.deviceIdDisplayEl = this.connectPromptEl.createEl("div", {
      cls: "clawdian-device-id",
      attr: { style: "display: none;" }
    });
    const btnContainer = this.connectPromptEl.createEl("div", { cls: "clawdian-btn-container" });
    const connectBtn = btnContainer.createEl("button", {
      cls: "clawdian-connect-btn",
      text: "Connect"
    });
    connectBtn.addEventListener("click", async () => {
      connectBtn.setText("Connecting...");
      connectBtn.disabled = true;
      await this.tryConnect();
    });
    const setupCodeBtn = btnContainer.createEl("button", {
      cls: "clawdian-setup-code-btn",
      text: "Use Setup Code"
    });
    setupCodeBtn.addEventListener("click", () => {
      new SetupCodeModal(this.app, (url, token) => {
        this.plugin.settings.gatewayUrl = url;
        this.plugin.settings.gatewayToken = token;
        this.plugin.saveSettings();
        this.client.updateConfig(url, token);
        this.tryConnect();
      }).open();
    });
    this.loadingEl = container.createEl("div", {
      cls: "clawdian-loading",
      attr: { style: "display: none;" }
    });
    const spinner = this.loadingEl.createEl("div", { cls: "clawdian-spinner" });
    this.loadingEl.createEl("span", { text: "Waiting for agent response..." });
    this.inputContainerEl = container.createEl("div", {
      cls: "clawdian-input-container",
      attr: { style: "display: none;" }
    });
    this.inputEl = this.inputContainerEl.createEl("textarea", {
      cls: "clawdian-input",
      placeholder: "Type a message..."
    });
    const sendBtn = this.inputContainerEl.createEl("button", {
      cls: "clawdian-send-btn",
      text: "Send"
    });
    sendBtn.addEventListener("click", () => this.sendMessage());
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      }
    });
    this.client.onMessage = (text) => {
      var _a, _b;
      console.log("[Clawdian] UI received message:", text);
      try {
        const data = JSON.parse(text);
        console.log("[Clawdian] Parsed data:", data);
        if (data.message && data.message.role === "assistant" && data.message.content) {
          console.log("[Clawdian] Found direct chat payload, extracting text...");
          const message = data.message;
          if (message.content && Array.isArray(message.content)) {
            const textContent = message.content.filter((item) => item.type === "text").map((item) => item.text).join("");
            console.log("[Clawdian] Extracted text:", textContent);
            this.hideLoading();
            this.addMessage("agent", textContent);
            return;
          }
        }
        if (data.type === "event" && data.event === "chat") {
          console.log("[Clawdian] Found chat event, checking payload...");
          const message = (_a = data.payload) == null ? void 0 : _a.message;
          const state = (_b = data.payload) == null ? void 0 : _b.state;
          console.log("[Clawdian] Chat event state:", state);
          if (state === "final" && message) {
            console.log("[Clawdian] Processing final message, extracting text...");
            if (message.content && Array.isArray(message.content)) {
              const textContent = message.content.filter((item) => item.type === "text").map((item) => item.text).join("");
              console.log("[Clawdian] Extracted text from final chat event:", textContent);
              this.hideLoading();
              this.addMessage("agent", textContent);
              return;
            } else {
              console.log("[Clawdian] Message content not in expected array format");
            }
          } else if (state !== "final") {
            console.log("[Clawdian] Skipping non-final message (state:", state, ")");
          }
        }
        console.log("[Clawdian] Message does not match expected formats");
      } catch (e) {
        console.log("[Clawdian] Failed to parse as JSON:", e);
      }
      console.log("[Clawdian] Using fallback text handling");
      this.hideLoading();
      this.addMessage("agent", text);
    };
    this.client.onConnect = () => {
      console.log("[Clawdian] ChatView onConnect called");
      this.showConnected();
      this.fetchAndUpdateAgents();
    };
    this.client.onAgentsUpdated = (agents) => {
      this.populateAgentDropdown(agents);
    };
    this.client.onDisconnect = () => {
      console.log("[Clawdian] ChatView onDisconnect called");
      this.showDisconnected();
    };
    this.client.onAuthError = (msg) => {
      console.log("[Clawdian] Auth error in view:", msg);
    };
    this.client.onPairingRequired = (deviceId) => {
      this.showPairingRequired(deviceId);
    };
    if (this.client.isConnected()) {
      console.log("[Clawdian] Already connected, showing chat");
      this.showConnected();
    }
  }
  async tryConnect() {
    var _a;
    const connectBtn = (_a = this.connectPromptEl) == null ? void 0 : _a.querySelector(".clawdian-connect-btn");
    try {
      await this.client.connect();
    } catch (err) {
      console.log("[Clawdian] Connection failed:", err.message);
      if (err.message.includes("pairing") || err.message.includes("device") || err.message.includes("unauthorized")) {
      } else {
        if (connectBtn) {
          connectBtn.setText("Connect");
          connectBtn.disabled = false;
        }
        new import_obsidian4.Notice("Connection failed: " + err.message);
      }
    }
  }
  async fetchAndUpdateAgents() {
    const agents = await this.client.fetchAgents();
    this.populateAgentDropdown(agents);
  }
  populateAgentDropdown(agents) {
    if (!this.agentSelectEl)
      return;
    this.agentSelectEl.empty();
    const agentsList = (agents == null ? void 0 : agents.length) ? agents : this.client.getAgents();
    if (agentsList.length === 0) {
      const option = this.agentSelectEl.createEl("option", {
        text: "No agents available",
        value: "",
        attr: { disabled: "true", selected: "true" }
      });
    } else {
      agentsList.forEach((agent) => {
        const option = this.agentSelectEl.createEl("option", {
          text: agent.name || agent.id,
          value: agent.id
        });
        if (agent.id === this.plugin.settings.defaultAgent) {
          option.selected = true;
        }
      });
    }
  }
  showConnected() {
    console.log("[Clawdian] showConnected called");
    if (this.connectPromptEl) {
      this.connectPromptEl.style.display = "none";
      console.log("[Clawdian] Hid connect prompt");
    }
    if (this.inputContainerEl) {
      this.inputContainerEl.style.display = "flex";
      console.log("[Clawdian] Showed input container");
    }
    this.addMessage("agent", "\u2705 Connected to OpenClaw!");
  }
  showDisconnected() {
    if (this.connectPromptEl) {
      this.connectPromptEl.style.display = "block";
      const connectBtn = this.connectPromptEl.querySelector(".clawdian-connect-btn");
      if (connectBtn) {
        connectBtn.setText("Connect");
        connectBtn.disabled = false;
      }
      const title = this.connectPromptEl.querySelector(".clawdian-connect-title");
      if (title)
        title.setText("Not Connected");
      const desc = this.connectPromptEl.querySelector(".clawdian-connect-desc");
      if (desc)
        desc.setText("Click Connect to start chatting with your OpenClaw agents.");
      if (this.deviceIdDisplayEl) {
        this.deviceIdDisplayEl.style.display = "none";
      }
    }
    if (this.inputContainerEl) {
      this.inputContainerEl.style.display = "none";
    }
  }
  showPairingRequired(deviceId) {
    if (!this.connectPromptEl)
      return;
    const title = this.connectPromptEl.querySelector(".clawdian-connect-title");
    if (title)
      title.setText("Pairing Required");
    const desc = this.connectPromptEl.querySelector(".clawdian-connect-desc");
    if (desc) {
      desc.setText("To authorize this device, run the command below in your terminal:");
    }
    if (this.deviceIdDisplayEl) {
      this.deviceIdDisplayEl.empty();
      this.deviceIdDisplayEl.style.display = "block";
      const cmdEl = this.deviceIdDisplayEl.createEl("div", { cls: "clawdian-terminal-command" });
      cmdEl.createEl("code", { text: `openclaw pairing approve ${deviceId}` });
      const copyBtn = this.deviceIdDisplayEl.createEl("button", {
        cls: "clawdian-copy-btn",
        text: "Copy Command"
      });
      copyBtn.addEventListener("click", () => {
        navigator.clipboard.writeText(`openclaw pairing approve ${deviceId}`);
        new import_obsidian4.Notice("Command copied to clipboard!");
      });
      this.deviceIdDisplayEl.createEl("div", {
        cls: "clawdian-device-id-label",
        text: `Device ID: ${deviceId}`
      });
    }
    const connectBtn = this.connectPromptEl.querySelector(".clawdian-connect-btn");
    if (connectBtn) {
      connectBtn.setText("Retry Connection");
      connectBtn.disabled = false;
    }
  }
  async sendMessage() {
    if (!this.client.isConnected()) {
      new import_obsidian4.Notice("Not connected. Click Connect first.");
      return;
    }
    if (this.isLoading) {
      return;
    }
    const text = this.inputEl.value.trim();
    if (!text)
      return;
    this.addMessage("user", text);
    this.inputEl.value = "";
    this.showLoading();
    const context = {};
    console.log("[Clawdian] includeVaultContext setting:", this.plugin.settings.includeVaultContext);
    if (this.plugin.settings.includeVaultContext) {
      const activeFile = this.app.workspace.getActiveFile();
      console.log("[Clawdian] Active file:", activeFile == null ? void 0 : activeFile.path);
      if (activeFile) {
        context.currentFile = activeFile.path;
        try {
          const content = await this.app.vault.read(activeFile);
          context.fileContent = content.slice(0, 5e3);
          console.log("[Clawdian] Context prepared - file:", context.currentFile, "content length:", context.fileContent.length);
        } catch (e) {
          console.log("[Clawdian] Could not read file:", e);
        }
      } else {
        console.log("[Clawdian] No active file found");
      }
    } else {
      console.log("[Clawdian] Vault context disabled in settings");
    }
    try {
      await this.client.sendMessage({
        agent: this.plugin.settings.defaultAgent,
        content: text,
        context
      });
    } catch (err) {
      this.addMessage("agent", "\u26A0\uFE0F Failed to send. Connection lost?");
    }
  }
  showLoading() {
    this.isLoading = true;
    if (this.loadingEl) {
      this.loadingEl.style.display = "flex";
    }
  }
  hideLoading() {
    this.isLoading = false;
    if (this.loadingEl) {
      this.loadingEl.style.display = "none";
    }
  }
  addMessage(sender, text) {
    console.log("[Clawdian] addMessage called with sender:", sender, "text:", text);
    const msgEl = this.messagesEl.createEl("div", {
      cls: `clawdian-message clawdian-message-${sender}`
    });
    msgEl.createEl("div", {
      cls: "clawdian-message-sender",
      text: sender === "user" ? "You" : this.plugin.settings.defaultAgent
    });
    msgEl.createEl("div", {
      cls: "clawdian-message-text",
      text
    });
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
    console.log("[Clawdian] Message added to UI");
  }
};

// src/utils/DeviceIdentity.ts
var import_obsidian5 = require("obsidian");
var _DeviceIdentityManager = class {
  constructor() {
    this.identity = null;
    this.deviceToken = null;
  }
  /**
   * Load or create device identity
   */
  async loadIdentity() {
    const stored = localStorage.getItem(_DeviceIdentityManager.STORAGE_KEY);
    if (stored) {
      this.identity = JSON.parse(stored);
      return this.identity;
    }
    this.identity = await this.generateIdentity();
    this.saveIdentity();
    return this.identity;
  }
  /**
   * Generate a new device identity with keypair
   */
  async generateIdentity() {
    const id = this.generateDeviceId();
    const keyPair = await crypto.subtle.generateKey(
      {
        name: "ECDSA",
        namedCurve: "P-256"
      },
      true,
      ["sign", "verify"]
    );
    const publicKeyBuffer = await crypto.subtle.exportKey("raw", keyPair.publicKey);
    const privateKeyBuffer = await crypto.subtle.exportKey("pkcs8", keyPair.privateKey);
    const publicKey = this.arrayBufferToBase64(publicKeyBuffer);
    const privateKey = this.arrayBufferToBase64(privateKeyBuffer);
    return {
      id,
      publicKey,
      privateKey,
      createdAt: Date.now()
    };
  }
  /**
   * Generate a stable device ID
   */
  generateDeviceId() {
    const random = Math.random().toString(36).substring(2, 10);
    return `clawdian-${import_obsidian5.Platform.isMacOS ? "macos" : import_obsidian5.Platform.isWin ? "windows" : "linux"}-${random}`;
  }
  /**
   * Save identity to localStorage
   */
  saveIdentity() {
    if (this.identity) {
      localStorage.setItem(_DeviceIdentityManager.STORAGE_KEY, JSON.stringify(this.identity));
    }
  }
  /**
   * Get device identity
   */
  getIdentity() {
    return this.identity;
  }
  /**
   * Get device ID
   */
  getDeviceId() {
    var _a;
    return ((_a = this.identity) == null ? void 0 : _a.id) || null;
  }
  /**
   * Sign a challenge nonce
   */
  async signChallenge(nonce) {
    if (!this.identity)
      return null;
    try {
      const privateKeyBuffer = this.base64ToArrayBuffer(this.identity.privateKey);
      const privateKey = await crypto.subtle.importKey(
        "pkcs8",
        privateKeyBuffer,
        { name: "ECDSA", namedCurve: "P-256" },
        false,
        ["sign"]
      );
      const timestamp = Date.now();
      const payload = JSON.stringify({
        nonce,
        deviceId: this.identity.id,
        timestamp,
        publicKey: this.identity.publicKey
      });
      const encoder = new TextEncoder();
      const signature = await crypto.subtle.sign(
        { name: "ECDSA", hash: "SHA-256" },
        privateKey,
        encoder.encode(payload)
      );
      return this.arrayBufferToBase64(signature);
    } catch (err) {
      console.error("[Clawdian] Failed to sign challenge:", err);
      return null;
    }
  }
  /**
   * Save device token from Gateway
   */
  saveDeviceToken(token) {
    this.deviceToken = token;
    localStorage.setItem(_DeviceIdentityManager.TOKEN_KEY, token);
  }
  /**
   * Load device token
   */
  loadDeviceToken() {
    if (!this.deviceToken) {
      this.deviceToken = localStorage.getItem(_DeviceIdentityManager.TOKEN_KEY);
    }
    return this.deviceToken;
  }
  /**
   * Clear device token (for re-pairing)
   */
  clearDeviceToken() {
    this.deviceToken = null;
    localStorage.removeItem(_DeviceIdentityManager.TOKEN_KEY);
  }
  /**
   * Clear all identity data
   */
  clearIdentity() {
    this.identity = null;
    this.deviceToken = null;
    localStorage.removeItem(_DeviceIdentityManager.STORAGE_KEY);
    localStorage.removeItem(_DeviceIdentityManager.TOKEN_KEY);
  }
  /**
   * Convert ArrayBuffer to base64
   */
  arrayBufferToBase64(buffer) {
    const bytes = new Uint8Array(buffer);
    let binary = "";
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }
  /**
   * Convert base64 to ArrayBuffer
   */
  base64ToArrayBuffer(base64) {
    const binary = atob(base64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
      bytes[i] = binary.charCodeAt(i);
    }
    return bytes.buffer;
  }
};
var DeviceIdentityManager = _DeviceIdentityManager;
DeviceIdentityManager.STORAGE_KEY = "clawdian-device-identity";
DeviceIdentityManager.TOKEN_KEY = "clawdian-device-token";

// src/utils/OpenClawClient.ts
var OpenClawClient = class {
  constructor(url, token) {
    this.ws = null;
    this.connected = false;
    this.connectionResolve = null;
    this.connectionReject = null;
    this.onMessage = null;
    this.onError = null;
    this.onConnect = null;
    this.onDisconnect = null;
    this.onAuthError = null;
    this.onPairingRequired = null;
    this.onAgentsUpdated = null;
    this.agents = [];
    this.url = url;
    this.token = token;
    this.deviceManager = new DeviceIdentityManager();
  }
  getAgents() {
    return this.agents;
  }
  async fetchAgents() {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) {
      console.log("[Clawdian] Cannot fetch agents - not connected");
      return [];
    }
    return new Promise((resolve) => {
      const requestId = this.generateId();
      const timeout = setTimeout(() => {
        console.log("[Clawdian] Agent fetch timeout");
        resolve([]);
      }, 5e3);
      const originalHandler = this.handleMessage.bind(this);
      this.handleMessage = async (data) => {
        var _a;
        if (data.id === requestId) {
          clearTimeout(timeout);
          this.handleMessage = originalHandler;
          if (data.type === "res" && ((_a = data.payload) == null ? void 0 : _a.agents)) {
            this.agents = data.payload.agents;
            if (this.onAgentsUpdated) {
              this.onAgentsUpdated(this.agents);
            }
            resolve(this.agents);
          } else {
            console.log("[Clawdian] No agents in response:", data);
            resolve([]);
          }
        } else {
          originalHandler(data);
        }
      };
      const request = {
        type: "req",
        id: requestId,
        method: "agents.list",
        params: {}
      };
      console.log("[Clawdian] Requesting agents list via WebSocket:", request);
      this.ws.send(JSON.stringify(request));
    });
  }
  updateConfig(url, token) {
    this.url = url;
    this.token = token;
    if (this.ws) {
      this.disconnect();
    }
  }
  isConnected() {
    return this.connected;
  }
  async connect() {
    try {
      await this.deviceManager.loadIdentity();
    } catch (e) {
      console.log("[Clawdian] Device identity not available");
    }
    return new Promise((resolve, reject) => {
      this.connectionResolve = resolve;
      this.connectionReject = reject;
      try {
        console.log("[Clawdian] Connecting to:", this.url);
        this.ws = new WebSocket(this.url);
        this.ws.onopen = () => {
          console.log("[Clawdian] WebSocket connected, waiting for challenge...");
        };
        this.ws.onmessage = async (event) => {
          try {
            const data = JSON.parse(event.data);
            await this.handleMessage(data);
          } catch (e) {
            console.log("[Clawdian] Received non-JSON message:", event.data);
            if (this.onMessage) {
              this.onMessage(event.data);
            }
          }
        };
        this.ws.onerror = (err) => {
          console.error("[Clawdian] WebSocket error:", err);
          const error = new Error("WebSocket connection failed");
          if (this.onError)
            this.onError(error);
          if (this.connectionReject) {
            this.connectionReject(error);
            this.connectionReject = null;
            this.connectionResolve = null;
          }
        };
        this.ws.onclose = () => {
          console.log("[Clawdian] WebSocket closed");
          this.connected = false;
          if (this.onDisconnect)
            this.onDisconnect();
        };
      } catch (err) {
        reject(err);
      }
    });
  }
  /**
   * Request pairing - user needs to approve this device
   */
  async requestPairing() {
    const identity = this.deviceManager.getIdentity();
    if (!identity) {
      await this.deviceManager.loadIdentity();
    }
    const deviceId = this.getDeviceId();
    if (!deviceId) {
      throw new Error("No device ID available");
    }
    if (this.onPairingRequired) {
      this.onPairingRequired(deviceId);
    }
  }
  /**
   * Handle Gateway messages
   */
  async handleMessage(data) {
    var _a, _b, _c, _d, _e, _f;
    console.log("[Clawdian] Received:", data.type, data);
    switch (data.type) {
      case "event":
        if (data.event === "connect.challenge") {
          console.log("[Clawdian] Challenge received, signing...");
          await this.handleChallenge((_a = data.payload) == null ? void 0 : _a.nonce);
        } else if (data.event === "chat" && ((_b = data.payload) == null ? void 0 : _b.message)) {
          console.log("[Clawdian] Chat event received, calling onMessage");
          if (this.onMessage) {
            this.onMessage(JSON.stringify(data));
          }
        }
        break;
      case "res":
        if (((_c = data.payload) == null ? void 0 : _c.type) === "hello-ok") {
          this.connected = true;
          console.log("[Clawdian] Connect successful (hello-ok)");
          if ((_e = (_d = data.payload) == null ? void 0 : _d.auth) == null ? void 0 : _e.deviceToken) {
            this.deviceManager.saveDeviceToken(data.payload.auth.deviceToken);
            console.log("[Clawdian] Device token saved");
          }
          if (this.onConnect)
            this.onConnect();
          if (this.connectionResolve) {
            this.connectionResolve();
            this.connectionResolve = null;
            this.connectionReject = null;
          }
        } else if (data.error) {
          const errorMsg = data.error.message || data.error || "Auth failed";
          console.error("[Clawdian] Auth error:", errorMsg);
          if (errorMsg.includes("pairing") || errorMsg.includes("device") || errorMsg.includes("unauthorized")) {
            console.log("[Clawdian] Pairing required");
            const deviceId = this.getDeviceId();
            if (deviceId && this.onPairingRequired) {
              this.onPairingRequired(deviceId);
            }
          }
          if (this.onAuthError)
            this.onAuthError(errorMsg);
          if (this.connectionReject) {
            this.connectionReject(new Error(errorMsg));
            this.connectionResolve = null;
            this.connectionReject = null;
          }
        }
        break;
      case "auth":
      case "connected":
        if (data.ok === true || data.type === "connected") {
          this.connected = true;
          console.log("[Clawdian] Auth successful, connected =", this.connected);
          if (data.deviceToken) {
            this.deviceManager.saveDeviceToken(data.deviceToken);
            console.log("[Clawdian] Device token saved");
          }
          if (this.onConnect) {
            console.log("[Clawdian] Calling onConnect callback");
            this.onConnect();
          }
          if (this.connectionResolve) {
            this.connectionResolve();
            this.connectionResolve = null;
            this.connectionReject = null;
          }
        }
        break;
      case "message":
        if (this.onMessage && ((_f = data.payload) == null ? void 0 : _f.content)) {
          this.onMessage(data.payload.content);
        } else if (this.onMessage && typeof data.payload === "string") {
          this.onMessage(data.payload);
        }
        break;
      default:
        console.log("[Clawdian] Unknown message type:", data.type);
    }
  }
  /**
   * Handle connect challenge by sending proper connect request
   */
  async handleChallenge(nonce) {
    var _a;
    if (!nonce) {
      console.error("[Clawdian] No nonce in challenge");
      return;
    }
    console.log("[Clawdian] Sending connect request with token");
    const connectRequest = {
      type: "req",
      id: this.generateId(),
      method: "connect",
      params: {
        minProtocol: 3,
        maxProtocol: 3,
        client: {
          id: "cli",
          version: "0.1.0",
          platform: "macos",
          mode: "ui"
          // REQUIRED: ui mode for Obsidian plugin (desktop UI client)
        },
        role: "operator",
        scopes: ["operator.read", "operator.write", "operator.admin"],
        auth: {
          token: this.token
        }
      }
    };
    console.log("[Clawdian] Connect request:", JSON.stringify(connectRequest, null, 2));
    (_a = this.ws) == null ? void 0 : _a.send(JSON.stringify(connectRequest));
  }
  /**
   * Fallback auth without device identity
   */
  sendLegacyAuth() {
    var _a;
    const authMessage = this.token ? { type: "auth", token: this.token } : { type: "auth" };
    console.log("[Clawdian] Sending legacy auth");
    (_a = this.ws) == null ? void 0 : _a.send(JSON.stringify(authMessage));
  }
  /**
   * Generate random ID
   */
  generateId() {
    return Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
  }
  /**
   * Get platform string
   */
  getPlatform() {
    const platform = navigator.platform.toLowerCase();
    if (platform.includes("mac"))
      return "macos";
    if (platform.includes("win"))
      return "windows";
    if (platform.includes("linux"))
      return "linux";
    return "unknown";
  }
  getDeviceId() {
    return this.deviceManager.getDeviceId();
  }
  clearDeviceToken() {
    this.deviceManager.clearDeviceToken();
  }
  sendMessage(msg) {
    return new Promise((resolve, reject) => {
      if (!this.ws || this.ws.readyState !== WebSocket.OPEN) {
        reject(new Error("Not connected"));
        return;
      }
      const request = {
        type: "req",
        id: "msg-" + this.generateId(),
        method: "chat.send",
        params: {
          sessionKey: msg.agent,
          // Just the agent name
          message: msg.content,
          idempotencyKey: this.generateId()
        }
      };
      console.log("[Clawdian] Sending message via WebSocket:", request);
      this.ws.send(JSON.stringify(request));
      resolve();
    });
  }
  disconnect() {
    if (this.ws) {
      this.ws.close();
      this.ws = null;
    }
    this.connected = false;
  }
};

// src/main.ts
var ClawdianPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    this.client = new OpenClawClient(
      this.settings.gatewayUrl,
      this.settings.gatewayToken
    );
    this.setupClientCallbacks();
    this.registerView(
      VIEW_TYPE_CHAT,
      (leaf) => new ChatView(leaf, this.client, this)
    );
    this.addRibbonIcon("message-square", "Open Clawdian", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-clawdian",
      name: "Open Clawdian chat",
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "c" }],
      callback: () => this.activateView()
    });
    this.addSettingTab(new ClawdianSettingTab(this.app, this));
    console.log("[Clawdian] Plugin loaded. Click \u{1F99E} to connect.");
  }
  setupClientCallbacks() {
    this.client.onConnect = () => {
      console.log("[Clawdian] Connected to Gateway");
      new import_obsidian6.Notice("\u{1F99E} Connected to OpenClaw!");
    };
    this.client.onDisconnect = () => {
      console.log("[Clawdian] Disconnected from Gateway");
    };
    this.client.onError = (err) => {
      console.error("[Clawdian] Client error:", err);
    };
    this.client.onAuthError = (msg) => {
      console.error("[Clawdian] Auth error:", msg);
      if (msg.includes("pairing") || msg.includes("token") || msg.includes("auth")) {
        const deviceId = this.client.getDeviceId();
        if (deviceId) {
          new PairingModal(this.app, deviceId, () => {
          }).open();
        }
      }
    };
  }
  async tryConnect() {
    try {
      await this.client.connect();
      return true;
    } catch (err) {
      console.error("[Clawdian] Connection failed:", err.message);
      new import_obsidian6.Notice("\u274C Connection failed: " + err.message);
      const deviceId = this.client.getDeviceId();
      if (deviceId) {
        new PairingModal(this.app, deviceId, () => {
        }).open();
      }
      return false;
    }
  }
  onunload() {
    var _a;
    (_a = this.client) == null ? void 0 : _a.disconnect();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_CHAT);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (!leaf)
        return;
      await leaf.setViewState({ type: VIEW_TYPE_CHAT, active: true });
    }
    workspace.revealLeaf(leaf);
    if (!this.client.isConnected()) {
      const connected = await this.tryConnect();
      if (!connected) {
      }
    }
  }
};
